name: Release & Publish to PyPI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build package
    uses: ./.github/workflows/build.yml

  publish:
    name: Publish and Release
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/gbatchkit
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download built distributions
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Create and Publish GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "v${{ needs.build.outputs.version }}"
        name: "v${{ needs.build.outputs.version }}"
        generate_release_notes: true
        files: |
          dist/*
